# Generated by Django 5.1.3 on 2024-11-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allowed_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
