# Generated by Django 5.1.3 on 2024-11-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='success',
            field=models.BooleanField(),
        ),
    ]
