# Generated by Django 5.1.3 on 2024-11-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_address_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nick_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nick Name'),
        ),
    ]
