# Generated by Django 5.1.3 on 2024-11-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_denied_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plain_text_pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
