# Generated by Django 5.1.3 on 2024-11-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_plain_text_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pin',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='plain_text_pin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
