# Generated by Django 5.1.3 on 2024-11-29 11:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customaccesslog_delete_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customaccesslog',
            name='custom_attempt_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customaccesslog',
            name='custom_ip_address',
            field=models.GenericIPAddressField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customaccesslog',
            name='custom_path_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customaccesslog',
            name='custom_user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customaccesslog',
            name='custom_username',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customaccesslog',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
