# Generated by Django 5.1.3 on 2024-11-29 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customaccesslog_custom_attempt_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='plain_text_pin',
        ),
    ]
