# Generated by Django 5.1.3 on 2024-11-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_customuser_plain_text_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enforce_url_restrictions',
            field=models.BooleanField(default=True, verbose_name='Enforce URL Restrictions'),
        ),
    ]
