# Generated by Django 5.1.3 on 2024-12-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_enforce_url_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Is Locked'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lock_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lock Until'),
        ),
    ]
