# Generated by Django 5.1.3 on 2024-11-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_imperial_units', models.BooleanField(default=False)),
                ('currency_type', models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£')], default='EUR', max_length=3)),
            ],
        ),
    ]
