# Generated by Django 5.1.3 on 2024-11-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_settings_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='use_imperial_units',
        ),
    ]
