# Generated by Django 5.1.3 on 2024-11-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_remove_settings_use_imperial_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='theme',
            field=models.CharField(choices=[('light', 'Light Theme'), ('dark', 'Dark Theme')], default='light', max_length=10),
        ),
    ]
