# Generated by Django 5.1.3 on 2024-11-14 15:05

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'), 
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='global', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalIngredient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('quantity', models.FloatField()),
                ('unit_type', models.CharField(choices=[('g', 'gram'), ('ml', 'milliliter'), ('pce', 'piece'), ('cm', 'centimeter')], max_length=10)),
                ('unit_multiplier', models.FloatField()),
                ('unit_cost', models.FloatField()),
                ('threshold', models.FloatField()),
                ('estimated_usage', models.FloatField(blank=True, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.category')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ingredient',
                'verbose_name_plural': 'historical ingredients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('quantity', models.FloatField()),
                ('unit_type', models.CharField(choices=[('g', 'gram'), ('ml', 'milliliter'), ('pce', 'piece'), ('cm', 'centimeter')], max_length=10)),
                ('unit_multiplier', models.FloatField()),
                ('unit_cost', models.FloatField()),
                ('threshold', models.FloatField()),
                ('estimated_usage', models.FloatField(blank=True, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
            ],
        ),
    ]
