# Generated by Django 5.1.3 on 2024-11-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_historicalingredient_unit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalingredient',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
