# Generated by Django 5.1.3 on 2024-11-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_category_id_alter_historicalingredient_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='historicalingredient',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
