# Generated by Django 5.1.3 on 2024-11-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_ingredient_options_historicalingredient_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalingredient',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'category')},
        ),
    ]
