# Generated by Django 5.1.3 on 2024-11-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingredient',
            name='change_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='change_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
