# Generated by Django 5.1.3 on 2024-11-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_historicalingredient_change_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalingredient',
            name='unit_type',
            field=models.CharField(choices=[('g', 'gram'), ('ml', 'milliliter'), ('pce', 'piece'), ('cm', 'centimeter'), ('oz', 'ounce'), ('fl_oz', 'fluid ounce'), ('in', 'inch')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_type',
            field=models.CharField(choices=[('g', 'gram'), ('ml', 'milliliter'), ('pce', 'piece'), ('cm', 'centimeter'), ('oz', 'ounce'), ('fl_oz', 'fluid ounce'), ('in', 'inch')], max_length=10),
        ),
    ]
