# Generated by Django 5.1.3 on 2024-11-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_historicalingredient_unit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingredient',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
