# Generated by Django 5.1.3 on 2024-11-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_historicalingredient_slug_ingredient_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
