# Generated by Django 5.1.3 on 2024-11-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalingredient',
            name='total_cost',
            field=models.DecimalField(decimal_places=6, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='total_cost',
            field=models.DecimalField(decimal_places=6, editable=False, max_digits=12),
        ),
    ]
