# Generated by Django 5.1.3 on 2024-11-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_historicalingredient_total_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='ingredients', to='inventory.allergen'),
        ),
    ]
