# Generated by Django 5.1.3 on 2024-11-25 15:57

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_allergen_ingredient_allergens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_prepped',
            field=models.BooleanField(default=False, help_text='Is this category for prepped ingredients?'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='Parent category for prepped ingredients.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_categories', to='inventory.category'),
        ),
        migrations.CreateModel(
            name='HistoricalPreppedIngredient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('quantity', models.FloatField()),
                ('prep_quantity', models.FloatField()),
                ('unit_type', models.CharField(choices=[('g', 'gram'), ('ml', 'milliliter'), ('pce', 'piece'), ('cm', 'centimeter'), ('oz', 'ounce'), ('fl_oz', 'fluid ounce'), ('in', 'inch')], max_length=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_prepped': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.category')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_ingredient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.ingredient')),
            ],
            options={
                'verbose_name': 'historical prepped ingredient',
                'verbose_name_plural': 'historical prepped ingredients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PreppedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('quantity', models.FloatField()),
                ('prep_quantity', models.FloatField()),
                ('unit_type', models.CharField(choices=[('g', 'gram'), ('ml', 'milliliter'), ('pce', 'piece'), ('cm', 'centimeter'), ('oz', 'ounce'), ('fl_oz', 'fluid ounce'), ('in', 'inch')], max_length=10)),
                ('category', models.ForeignKey(limit_choices_to={'is_prepped': True}, on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('parent_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepped_ingredients', to='inventory.ingredient')),
            ],
        ),
    ]
