# Generated by Django 5.1.3 on 2024-11-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_category_is_prepped_category_parent_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingredient',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
