# Generated by Django 5.1.3 on 2024-11-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_historicalingredient_visible_ingredient_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingredient',
            name='waste_reason',
            field=models.TextField(blank=True, help_text='Reason for wastage (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='waste_reason',
            field=models.TextField(blank=True, help_text='Reason for wastage (if applicable)', null=True),
        ),
    ]
