# Generated by Django 5.1.3 on 2024-11-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_historicalingredient_waste_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingredient',
            name='unit_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit_name',
            field=models.CharField(default='whoa', max_length=100),
            preserve_default=False,
        ),
    ]
