# Generated by Django 5.1.3 on 2024-11-30 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_historicalingredient_unit_name_ingredient_unit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalingredient',
            name='unit_name',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit_name',
        ),
    ]
