# Generated by Django 5.1.3 on 2024-11-30 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_ingredientunit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngredientUnit',
        ),
    ]
