# Generated by Django 5.1.3 on 2024-12-01 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_delete_ingredientunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit_type', models.CharField(choices=[('g', 'gram'), ('ml', 'milliliter'), ('pce', 'piece'), ('cm', 'centimeter'), ('oz', 'ounce'), ('fl_oz', 'fluid ounce'), ('in', 'inch')], max_length=10)),
                ('unit_multiplier', models.FloatField()),
                ('quantity', models.FloatField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='inventory.ingredient')),
            ],
        ),
    ]
