# Generated by Django 5.1.3 on 2024-12-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_unit_delete_ingredientunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
