# Generated by Django 5.1.3 on 2024-12-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_historicalunit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalUnit',
        ),
    ]
