# Generated by Django 5.1.3 on 2024-12-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_historicalunit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalUnit',
        ),
    ]
