# Generated by Django 5.1.3 on 2024-12-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_cartitem_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sumup_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('digital', 'Digital'), ('sumup', 'SumUp Terminal')], max_length=50),
        ),
    ]
