# Generated by Django 5.1.3 on 2024-11-21 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_historicalingredient_unit_type_and_more'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category to deplete from', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
        ),
    ]
