# Generated by Django 5.1.3 on 2024-11-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menucategory_options_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
