# Generated by Django 5.1.3 on 2024-11-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_menuitem_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
