# Generated by Django 5.1.3 on 2024-11-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_menuitem_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
