# Generated by Django 5.1.3 on 2024-11-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_menucategory_is_active_menuitem_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
