# Generated by Django 5.1.3 on 2024-12-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_menuitem_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_secondary',
            field=models.BooleanField(default=False),
        ),
    ]
