# Generated by Django 5.1.3 on 2024-12-05 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_menuitem_is_secondary'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='primary_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_items', to='menu.menuitem'),
        ),
    ]
