# Generated by Django 5.1.3 on 2024-12-05 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_menuitem_primary_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='primary_item',
        ),
    ]
