# Generated by Django 5.1.3 on 2024-12-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_remove_menuitem_primary_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_secondary',
            field=models.BooleanField(default=False),
        ),
    ]
