# Generated by Django 5.1.3 on 2024-12-08 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_menu_is_secondary'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='associated_secondary_menu',
            field=models.ForeignKey(blank=True, help_text='Select a secondary menu associated with this item.', limit_choices_to={'is_secondary': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menu'),
        ),
    ]
