# Generated by Django 5.1.3 on 2024-12-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_menuitem_associated_secondary_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='secondary_active',
            field=models.BooleanField(default=False, help_text='Indicates if the item is secondary active.'),
        ),
    ]
