# Generated by Django 5.1.3 on 2024-12-09 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_menuitem_associated_secondary_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemSecondaryAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_associations', to='menu.menuitem')),
                ('secondary_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='menu.menuitem')),
            ],
            options={
                'unique_together': {('menu_item', 'secondary_item')},
            },
        ),
    ]
