# Generated by Django 5.1.3 on 2024-12-10 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_menuitemvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='menu.menuitemvariation'),
        ),
    ]
