# Generated by Django 5.1.3 on 2024-12-10 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_historicalingredient_quantity_and_more'),
        ('menu', '0022_recipeingredient_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_recipe_ingredients', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variation_recipe_ingredients', to='menu.menuitemvariation'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('menu_item__isnull', False), _negated=True), models.Q(('variation__isnull', False), _negated=True), _connector='OR'), name='either_menu_item_or_variation'),
        ),
    ]
